package com.entity;

public class Goodsinfo {


     private String categorysname;

    private String goodsscore;//
    private String goodsinfoprice;//单价
    private String goodsinfo_1;//备用
    private String goodsinfo_2;//备用
    private String goodsinfo_3;//备用
    private String goodsinfo_4;//备用
    private String goodsinfo_5;//备用
    private String goodsinfo_6;//备用



    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.goodsinfoid
     *
     * @mbggenerated
     */
    private Integer goodsinfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.countrequire
     *
     * @mbggenerated
     */
    private Integer countrequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.iscooled
     *
     * @mbggenerated
     */
    private Integer iscooled;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.goodsinfoid
     *
     * @return the value of goodsinfo.goodsinfoid
     *
     * @mbggenerated
     */
    public Integer getGoodsinfoid() {
        return goodsinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.goodsinfoid
     *
     * @param goodsinfoid the value for goodsinfo.goodsinfoid
     *
     * @mbggenerated
     */
    public void setGoodsinfoid(Integer goodsinfoid) {
        this.goodsinfoid = goodsinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.status
     *
     * @return the value of goodsinfo.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.status
     *
     * @param status the value for goodsinfo.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.countrequire
     *
     * @return the value of goodsinfo.countrequire
     *
     * @mbggenerated
     */
    public Integer getCountrequire() {
        return countrequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.countrequire
     *
     * @param countrequire the value for goodsinfo.countrequire
     *
     * @mbggenerated
     */
    public void setCountrequire(Integer countrequire) {
        this.countrequire = countrequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.iscooled
     *
     * @return the value of goodsinfo.iscooled
     *
     * @mbggenerated
     */
    public Integer getIscooled() {
        return iscooled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.iscooled
     *
     * @param iscooled the value for goodsinfo.iscooled
     *
     * @mbggenerated
     */
    public void setIscooled(Integer iscooled) {
        this.iscooled = iscooled;
    }




    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.goodsinfoname
     *
     * @mbggenerated
     */
    private String goodsinfoname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodsinfo.createdate
     *
     * @mbggenerated
     */
    private String createdate;



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.goodsinfoname
     *
     * @return the value of goodsinfo.goodsinfoname
     *
     * @mbggenerated
     */
    public String getGoodsinfoname() {
        return goodsinfoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.goodsinfoname
     *
     * @param goodsinfoname the value for goodsinfo.goodsinfoname
     *
     * @mbggenerated
     */
    public void setGoodsinfoname(String goodsinfoname) {
        this.goodsinfoname = goodsinfoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.image
     *
     * @return the value of goodsinfo.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.image
     *
     * @param image the value for goodsinfo.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.remark
     *
     * @return the value of goodsinfo.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.remark
     *
     * @param remark the value for goodsinfo.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodsinfo.createdate
     *
     * @return the value of goodsinfo.createdate
     *
     * @mbggenerated
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodsinfo.createdate
     *
     * @param createdate the value for goodsinfo.createdate
     *
     * @mbggenerated
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }



    public String getCategorysname() {
        return categorysname;
    }

    public void setCategorysname(String categorysname) {
        this.categorysname = categorysname;
    }



    public String getGoodsscore() {
        return goodsscore;
    }

    public void setGoodsscore(String goodsscore) {
        this.goodsscore = goodsscore;
    }

    public String getGoodsinfoprice() {
        return goodsinfoprice;
    }

    public void setGoodsinfoprice(String goodsinfoprice) {
        this.goodsinfoprice = goodsinfoprice;
    }

    public String getGoodsinfo_1() {
        return goodsinfo_1;
    }

    public void setGoodsinfo_1(String goodsinfo_1) {
        this.goodsinfo_1 = goodsinfo_1;
    }

    public String getGoodsinfo_2() {
        return goodsinfo_2;
    }

    public void setGoodsinfo_2(String goodsinfo_2) {
        this.goodsinfo_2 = goodsinfo_2;
    }

    public String getGoodsinfo_3() {
        return goodsinfo_3;
    }

    public void setGoodsinfo_3(String goodsinfo_3) {
        this.goodsinfo_3 = goodsinfo_3;
    }

    public String getGoodsinfo_4() {
        return goodsinfo_4;
    }

    public void setGoodsinfo_4(String goodsinfo_4) {
        this.goodsinfo_4 = goodsinfo_4;
    }

    public String getGoodsinfo_5() {
        return goodsinfo_5;
    }

    public void setGoodsinfo_5(String goodsinfo_5) {
        this.goodsinfo_5 = goodsinfo_5;
    }

    public String getGoodsinfo_6() {
        return goodsinfo_6;
    }

    public void setGoodsinfo_6(String goodsinfo_6) {
        this.goodsinfo_6 = goodsinfo_6;
    }
}