package com.entity;

import org.springframework.stereotype.Component;

@Component
public class Thinginfo {


    private String classifyinfotitle;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thinginfo.thinginfoid
     *
     * @mbggenerated
     */
    private Integer thinginfoid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thinginfo.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thinginfo.countrequire
     *
     * @mbggenerated
     */
    private Integer countrequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thinginfo.thingprice
     *
     * @mbggenerated
     */
    private Integer thingprice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thinginfo.thinginfoid
     *
     * @return the value of thinginfo.thinginfoid
     * @mbggenerated
     */
    public Integer getThinginfoid() {
        return thinginfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thinginfo.thinginfoid
     *
     * @param thinginfoid the value for thinginfo.thinginfoid
     * @mbggenerated
     */
    public void setThinginfoid(Integer thinginfoid) {
        this.thinginfoid = thinginfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thinginfo.status
     *
     * @return the value of thinginfo.status
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thinginfo.status
     *
     * @param status the value for thinginfo.status
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thinginfo.countrequire
     *
     * @return the value of thinginfo.countrequire
     * @mbggenerated
     */
    public Integer getCountrequire() {
        return countrequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thinginfo.countrequire
     *
     * @param countrequire the value for thinginfo.countrequire
     * @mbggenerated
     */
    public void setCountrequire(Integer countrequire) {
        this.countrequire = countrequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thinginfo.thingprice
     *
     * @return the value of thinginfo.thingprice
     * @mbggenerated
     */
    public Integer getThingprice() {
        return thingprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thinginfo.thingprice
     *
     * @param thingprice the value for thinginfo.thingprice
     * @mbggenerated
     */
    public void setThingprice(Integer thingprice) {
        this.thingprice = thingprice;
    }


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thinginfo.thinginfoname
     *
     * @mbggenerated
     */
    private String thinginfoname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thinginfo.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thinginfo.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thinginfo.createdate
     *
     * @mbggenerated
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column thinginfo.classifyinfoid
     *
     * @mbggenerated
     */
    private String classifyinfoid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thinginfo.thinginfoname
     *
     * @return the value of thinginfo.thinginfoname
     * @mbggenerated
     */
    public String getThinginfoname() {
        return thinginfoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thinginfo.thinginfoname
     *
     * @param thinginfoname the value for thinginfo.thinginfoname
     * @mbggenerated
     */
    public void setThinginfoname(String thinginfoname) {
        this.thinginfoname = thinginfoname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thinginfo.image
     *
     * @return the value of thinginfo.image
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thinginfo.image
     *
     * @param image the value for thinginfo.image
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thinginfo.remark
     *
     * @return the value of thinginfo.remark
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thinginfo.remark
     *
     * @param remark the value for thinginfo.remark
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thinginfo.createdate
     *
     * @return the value of thinginfo.createdate
     * @mbggenerated
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thinginfo.createdate
     *
     * @param createdate the value for thinginfo.createdate
     * @mbggenerated
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column thinginfo.classifyinfoid
     *
     * @return the value of thinginfo.classifyinfoid
     * @mbggenerated
     */
    public String getClassifyinfoid() {
        return classifyinfoid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column thinginfo.classifyinfoid
     *
     * @param classifyinfoid the value for thinginfo.classifyinfoid
     * @mbggenerated
     */
    public void setClassifyinfoid(String classifyinfoid) {
        this.classifyinfoid = classifyinfoid;
    }

    public String getClassifyinfotitle() {
        return classifyinfotitle;
    }

    public void setClassifyinfotitle(String classifyinfotitle) {
        this.classifyinfotitle = classifyinfotitle;
    }


}